### ISSUE TITLE
It doesn't work when we delete！

### ISSUE THREAD

**Issue by LittlePeopleGang** [Serheo/SHSPhoneComponent#21]
help!
”### ### ###“
like this formatter，It doesn't work when we delete from the fourth character！
i read your code，found The error occurred in class(SHSPhoneLogic) 
Can you fix this problem? 
Because our project USES your framework, please

**Comment by Serheo** [comment]
Hey @LittlePeopleGang 
Which version of a framwork do you use?
what you you mean - doesn't work? just checked the demo app - seems working.
when you delete the 4th character - its delete the 4th char and the space before it if that's the last and just simbol if you delete in the center.

give me more details about that you think is an issue, and what is expected behaviour

**Comment by LittlePeopleGang** [comment]
Hey @Serheo 
The latest version 2.31
”158 6819 1992“
I expect the fourth character and space to be deleted when I delete the fourth character.
after delete，it looks like ”156 8191 992“

**Comment by Serheo** [comment]
try it out 2.32

**Comment by LittlePeopleGang** [comment]
> try it out 2.32

Thank you for your update！
But there seems to be a slight problem
formatter ”### #### ####“
input text ”158 6819 1992“
Input should not be allowed in this case, but now you can input before the last char

**Comment by Serheo** [comment]
I was thinking about that, but it always was this way - I mean you can type in the center of the full input.
Not sure if blocking an input in this case a good idea. do you think it's a problem?

**Comment by LittlePeopleGang** [comment]
> I was thinking about that, but it always was this way - I mean you can type in the center of the full input.
> Not sure if blocking an input in this case a good idea. do you think it's a problem?

I agree！That's the right way to do it！
God bless you！thank you！
